on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build (Jiran BLE Lite Left)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-jiran_ble_lite-left
        with:
          args: 'build "-s zmk/app -b jiran_ble_lite_left -- -DZMK_CONFIG=/github/workspace/config"'
      - name: Jiran BLE Lite Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 jiran_ble_lite_left.uf2
      - name: Archive (Jiran BLE Lite Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: jiran_ble_lite_left.uf2
      - name: West Build (Jiran BLE Lite Right)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-jiran_ble_lite-right
        with:
          args: 'build "--pristine -s zmk/app -b jiran_ble_lite_right -- -DZMK_CONFIG=/github/workspace/config"'
      - name: Jiran BLE Lite Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 jiran_ble_lite_right.uf2
      - name: Archive (Jiran BLE Lite Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: jiran_ble_lite_right.uf2
